import os

# 写入完整测试内容
test_lines = [
    'package config',
    '',
    'import (',
    '    "encoding/json"',
    '    "os"',
    '    "path/filepath"',
    '    "testing"',
    ')',
    '',
    'func TestGetDefault(t *testing.T) {',
    '    cfg := GetDefault()',
    '',
    '    if cfg.Serial.BaudRate != 115200 {',
    '        t.Errorf("默认波特率应为 115200，实际为 %d", cfg.Serial.BaudRate)',
    '    }',
    '    if cfg.Serial.DataBits != 8 {',
    '        t.Errorf("默认数据位应为 8，实际为 %d", cfg.Serial.DataBits)',
    '    }',
    '    if cfg.Serial.Parity != "none" {',
    '        t.Errorf("默认校验位应为 'none'，实际为 '%s'", cfg.Serial.Parity)',
    '    }',
    '    if cfg.Serial.StopBits != 1 {',
    '        t.Errorf("默认停止位应为 1，实际为 %d", cfg.Serial.StopBits)',
    '    }',
    '',
    '    if cfg.Telnet.Port != 2323 {',
    '        t.Errorf("默认 Telnet 端口应为 2323，实际为 %d", cfg.Telnet.Port)',
    '    }',
    '',
    '    if cfg.MCP.HTTPPort != 5000 {',
    '        t.Errorf("默认 MCP HTTP 端口应为 5000，实际为 %d", cfg.MCP.HTTPPort)',
    '    }',
    '',
    '    if cfg.Debug != false {',
    '        t.Errorf("默认 Debug 应为 false，实际为 %t", cfg.Debug)',
    '    }',
    '}',
    '',
    'func TestLoadConfig(t *testing.T) {',
    '    tmpDir := t.TempDir()',
    '    configPath := filepath.Join(tmpDir, "config.json")',
    '    configJSON :=  + "'" + {"serial":{"port":"COM9","baudRate":9600,"dataBits":8,"parity":"none","stopBits":1},"telnet":{"port":2324},"mcp":{"httpPort":5001},"debug":true} + "'" + ',
    '    if err := os.WriteFile(configPath, []byte(configJSON), 0644); err != nil {',
    '        t.Fatalf("failed to create config file: %v", err)',
    '    }',
    '    cfg, err := Load(configPath)',
    '    if err != nil {',
    '        t.Fatalf("failed to load config: %v", err)',
    '    }',
    '    if cfg.Serial.Port != "COM9" {',
    '        t.Errorf("expected port 'COM9', got '%s'", cfg.Serial.Port)',
    '    }',
    '    if cfg.Serial.BaudRate != 9600 {',
    '        t.Errorf("expected baud rate 9600, got %d", cfg.Serial.BaudRate)',
    '    }',
    '    if cfg.Telnet.Port != 2324 {',
    '        t.Errorf("expected telnet port 2324, got %d", cfg.Telnet.Port)',
    '    }',
    '    if cfg.MCP.HTTPPort != 5001 {',
    '        t.Errorf("expected mcp http port 5001, got %d", cfg.MCP.HTTPPort)',
    '    }',
    '    if cfg.Debug != true {',
    '        t.Errorf("expected debug true, got %t", cfg.Debug)',
    '    }',
    '}',
    '',
    'func TestLoadConfig_FileNotFound(t *testing.T) {',
    '    configPath := filepath.Join(t.TempDir(), "nonexistent.json")',
    '    cfg, err := Load(configPath)',
    '    if err != nil {',
    '        t.Fatalf("loading nonexistent config should return default config, got error: %v", err)',
    '    }',
    '    if cfg.Serial.BaudRate != 115200 {',
    '        t.Errorf("expected default baud rate 115200, got %d", cfg.Serial.BaudRate)',
    '    }',
    '    if cfg.Telnet.Port != 2323 {',
    '        t.Errorf("expected default telnet port 2323, got %d", cfg.Telnet.Port)',
    '    }',
    '}',
    '',
    'func TestLoadConfig_InvalidJSON(t *testing.T) {',
    '    tmpDir := t.TempDir()',
    '    configPath := filepath.Join(tmpDir, "invalid.json")',
    '    invalidJSON :=  + "'" + {"serial":{"port":"COM9","baudRate":"not-a-number"}} + "'" + ',
    '    if err := os.WriteFile(configPath, []byte(invalidJSON), 0644); err != nil {',
    '        t.Fatalf("failed to create config file: %v", err)',
    '    }',
    '    _, err := Load(configPath)',
    '    if err == nil {',
    '        t.Error("loading invalid JSON should return error")',
    '    }',
    '}',
    '',
    'func TestConfigMerge(t *testing.T) {',
    '    tmpDir := t.TempDir()',
    '    configPath := filepath.Join(tmpDir, "partial.json")',
    '    configJSON :=  + "'" + {"serial":{"port":"COM8","baudRate":57600},"mcp":{"httpPort":6000}} + "'" + ',
    '    if err := os.WriteFile(configPath, []byte(configJSON), 0644); err != nil {',
    '        t.Fatalf("failed to create config file: %v", err)',
    '    }',
    '    cfg, err := Load(configPath)',
    '    if err != nil {',
    '        t.Fatalf("failed to load config: %v", err)',
    '    }',
    '    if cfg.Serial.Port != "COM8" {',
    '        t.Errorf("expected port 'COM8', got '%s'", cfg.Serial.Port)',
    '    }',
    '    if cfg.Serial.BaudRate != 57600 {',
    '        t.Errorf("expected baud rate 57600, got %d", cfg.Serial.BaudRate)',
    '    }',
    '    if cfg.MCP.HTTPPort != 6000 {',
    '        t.Errorf("expected mcp http port 6000, got %d", cfg.MCP.HTTPPort)',
    '    }',
    '    if cfg.Serial.DataBits != 8 {',
    '        t.Errorf("unconfigured DataBits should use default 8, got %d", cfg.Serial.DataBits)',
    '    }',
    '    if cfg.Serial.Parity != "none" {',
    '        t.Errorf("unconfigured Parity should use default 'none', got '%s'", cfg.Serial.Parity)',
    '    }',
    '    if cfg.Telnet.Port != 2323 {',
    '        t.Errorf("unconfigured telnet port should use default 2323, got %d", cfg.Telnet.Port)',
    '    }',
    '}',
    '',
    'func TestConfig_EmptyPath(t *testing.T) {',
    '    cfg, err := Load("")',
    '    if err != nil {',
    '        t.Errorf("empty path should not return error: %v", err)',
    '    }',
    '    if cfg == nil {',
    '        t.Fatal("empty path should return default config, not nil")',
    '    }',
    '    defaultCfg := GetDefault()',
    '    if cfg.Serial.BaudRate != defaultCfg.Serial.BaudRate {',
    '        t.Errorf("empty path should use default config")',
    '    }',
    '}',
    '',
    'func TestConfig_ToJSON(t *testing.T) {',
    '    cfg := GetDefault()',
    '    cfg.Serial.Port = "COM9"',
    '    jsonStr, err := cfg.ToJSON()',
    '    if err != nil {',
    '        t.Errorf("config serialization failed: %v", err)',
    '    }',
    '    if jsonStr == "" {',
    '        t.Error("config serialization result should not be empty")',
    '    }',
    '    parsed := &Config{}',
    '    if err := json.Unmarshal([]byte(jsonStr), parsed); err != nil {',
    '        t.Errorf("serialized result cannot be deserialized: %v", err)',
    '    }',
    '    if parsed.Serial.Port != "COM9" {',
    '        t.Errorf("data inconsistency after serialization/deserialization")',
    '    }',
    '}',
]

with open('pkg/config/config_test.go', 'w', encoding='utf-8', newline='') as f:
    for line in test_lines:
        f.write(line + '\\n')

print('File created successfully')
